import { Montserrat } from 'next/font/google';
import type { Metadata } from "next";


import { Header } from '@/components/shared/header';
import { Footer } from '@/components/shared/footer';

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600'],
  variable: '--font-montserrat',
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import { Scroll } from '@/components/shared/scroll';
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} text-regal-black`}>
        <Scroll>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </Scroll>
      </body>
    </html>
  );
}
