import type { Metadata } from "next";

import { Header } from '@/components/shared/header';
import { Modal } from "@/components/shared/modal/modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MapaLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <>
      <Header canHide />
      <main>
        {children}
        <Modal />
      </main>
    </>
  );
}
